GET http://localhost:9090/testroutes

###
 
GET http://localhost:9090/testroutes/653902eabde35bdcaba0c4c8
###

POST http://localhost:9090/testroutes
Content-Type: application/json

{
    "name": "Imperial Guardsman",
    "paint": "blue, green",
    "brushes": "000"
}
###

DELETE http://localhost:9090/testroutes/6532a2c21ee5c45fea59a5b0
